### ISSUE TITLE
Impossible browse the courses with PyCharm Pro 2018.2

### ISSUE THREAD

**Issue by pavelnt** [JetBrains/educational-plugin#18]
Window with list of courses doesn't appear after press the button "Browse courses".

2018-07-26 00:26:52,244 [ 651891]   INFO - earning.stepik.StepikConnector - Loading courses started... 
2018-07-26 00:26:59,520 [ 659167]   INFO - earning.stepik.StepikConnector - Loading courses finished...Took 7275 ms 
2018-07-26 00:26:59,920 [ 659567]  ERROR - llij.ide.plugins.PluginManager - com.jetbrains.python.sdk.PythonSdkAdditionalData.getAssociatedProjectPath()Ljava/lang/String; 
java.lang.NoSuchMethodError: com.jetbrains.python.sdk.PythonSdkAdditionalData.getAssociatedProjectPath()Ljava/lang/String;
	at com.jetbrains.edu.python.learning.pycharm.PyLanguageSettings$getInterpreterComboBox$1.test(PyLanguageSettings.kt:20)
	at com.jetbrains.edu.python.learning.pycharm.PyLanguageSettings$getInterpreterComboBox$1.test(PyLanguageSettings.kt:12)
	at java.util.ArrayList.removeIf(ArrayList.java:1407)
	at com.jetbrains.edu.python.learning.pycharm.PyLanguageSettings.getInterpreterComboBox(PyLanguageSettings.kt:16)
	at com.jetbrains.edu.python.learning.newproject.PyLanguageSettings.getLanguageSettingsComponents(PyLanguageSettings.kt:35)
	at com.jetbrains.edu.learning.newproject.ui.CoursePanel.updateAdvancedSettings(CoursePanel.java:187)
	at com.jetbrains.edu.learning.newproject.ui.CoursePanel.bindCourse(CoursePanel.java:101)
	at com.jetbrains.edu.learning.newproject.ui.CoursesPanel.updateCourseInfoPanel(CoursesPanel.java:208)
	at com.jetbrains.edu.learning.newproject.ui.CoursesPanel.processSelectionChanged(CoursesPanel.java:189)
	at com.jetbrains.edu.learning.newproject.ui.CoursesPanel.initUI(CoursesPanel.java:141)
	at com.jetbrains.edu.learning.newproject.ui.CoursesPanel.<init>(CoursesPanel.java:82)
	at com.jetbrains.edu.learning.newproject.ui.BrowseCoursesDialog.<init>(BrowseCoursesDialog.kt:10)
	at com.jetbrains.edu.learning.newproject.BrowseCoursesAction.actionPerformed(BrowseCoursesAction.kt:13)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:347)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:334)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:60)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:142)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:69)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:326)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:781)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:718)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2018-07-26 00:26:59,921 [ 659568]  ERROR - llij.ide.plugins.PluginManager - PyCharm 2018.2  Build #PY-182.3684.100 
2018-07-26 00:26:59,921 [ 659568]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_152-release 
2018-07-26 00:26:59,921 [ 659568]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2018-07-26 00:26:59,922 [ 659569]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2018-07-26 00:26:59,922 [ 659569]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X

**Comment by Undin** [comment]
@pavelnt Thanks for the report!
We've already fixed it (see the corresponding [issue](https://youtrack.jetbrains.com/issue/EDU-1524) in our tracker) and it will be landed in next release
